### a


In [ ]:
import numpy as np

vector = np.random.randint(1, 21, size=15)
vector

array([ 4,  8, 19, 18, 14,  9,  7, 17,  1, 10, 16, 14, 20, 11, 18])

In [2]:
new_vector = vector.reshape(3,5)
display(new_vector)
print(new_vector.shape)

array([[ 4,  8, 19, 18, 14],
       [ 9,  7, 17,  1, 10],
       [16, 14, 20, 11, 18]])

(3, 5)


In [7]:
for i, row in enumerate(new_vector):
    maximum = max(row)
    new_vector[i][np.where(row == maximum)[0][0]] = 0
new_vector

array([[ 4,  8,  0, 18, 14],
       [ 9,  7,  0,  1, 10],
       [16, 14,  0, 11, 18]])

### b

In [11]:
array = np.random.randint(-100, 100, size=(4,3))
display(array)
print(array.shape)
print(type(array))
print(array.dtype)

array([[-34,   2,   4],
       [-93,   5,  65],
       [ 93,  40,  97],
       [-32, -10,  60]])

(4, 3)
<class 'numpy.ndarray'>
int32


### c


In [16]:
array = np.array([[3, -2],
                   [1, 0]])

eigenvalues, eigenvectors = np.linalg.eig(array)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[2. 1.]

Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


### d

In [14]:
array = np.array([[0,1,2],[3,4,5]])
summation = 0
for i,row in enumerate(array):
    summation += row[i]

print(summation)

4


### e

In [19]:
original = np.array([[1,2],[3,4],[5,6]])
new = original.copy().reshape(2,3)

display(original)
display(new)

array([[1, 2],
       [3, 4],
       [5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])